apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 2
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:8.4.4
        env:
        - name: GF_DATABASE_TYPE
          value: mysql
        - name: GF_DATABASE_HOST
          value: mysql.default.svc.cluster.local
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mysql
              key: user
        - name: GF_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: password  
        livenessProbe:
          httpGet:
            path: "/api/health" 
            port: 3000
        readinessProbe:
          httpGet:
            path: "/api/health" 
            port: 3000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
