apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  serviceName: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      initContainers:
      - name: init-chown-data
        image: busybox
        imagePullPolicy: Always
        command: ["chown", "-R", "65534:65534", "/prometheus"]
        volumeMounts:
        - name: data
          mountPath: /prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:v2.34.0
        command:
          - "sleep"
          - "infinity"
        # args:
        #   - --config.file=/etc/config/prometheus.yaml
        #   - --storage.tsdb.path=/prometheus
        #   - --web.console.libraries=/etc/prometheus/console_libraries
        #   - --web.console.templates=/etc/prometheus/consoles
        #   - --web.enable-lifecycle
        #   - --storage.tsdb.retention.size=8GB
        ports:
        - containerPort: 9090
        # livenessProbe:
        #   httpGet:
        #     path: "/-/healthy" 
        #     port: 9090
        # readinessProbe:
        #   httpGet:
        #     path: "/-/ready" 
        #     port: 9090
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "100m"
        volumeMounts:
        - name: data
          mountPath: /prometheus
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName:  standard
      resources:
        requests:
          storage: 10Gi

