name: Docker Image CI

on:
  push:
    branches: 
    - main
    - v**

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: [opener, rank-exporter]

    steps:
    - uses: actions/checkout@v2
    
    - name: Retrieve short sha
      run: echo "BRANCH_NAME=$GITHUB_REF_NAME" >> $GITHUB_ENV
    
    - name: Print env
      run: env | sort 

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build the shaunz-cards-${{ matrix.component }} Docker image
      uses: docker/build-push-action@v2
      with: 
        context: ${{ matrix.component }}
        file: ${{ matrix.component }}/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/shaunz-cards-${{ matrix.component }}:${{ env.BRANCH_NAME }}
              